using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO.Pipelines;
using System.Net;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Security.Cryptography;

namespace DDUP
{	
	public struct EventItemInfo
	{
		public string ItemName;
		public string HashPhrase;
		public string Category;
		public uint NumericHash;

		public int Price;

		public EventItemInfo(string itemName, string category, string hashPhrase, int price)
		{
			ItemName = itemName;
			Category = category;
			HashPhrase = hashPhrase;
			Price = price;
			NumericHash = 0;
			ItemHash.TryPhraseToInt30(hashPhrase, out NumericHash);
			EventPriceGuide.HashToEventInfo[NumericHash] = this;			
		}			
	}

	public static class EventPriceGuide
	{
		public static Dictionary<uint, EventItemInfo> HashToEventInfo = [];		
		public static readonly EventItemInfo[] EventInfo = 
		{
			new ("Admiral Djinn", "Pets > Collectibles", "Endless Grim Obelisk Builds Juicy Berserker", 41),
			new ("Ahoy", "Pets > DPS", "Shiny Wild Sigil Launches Sweaty Raider", 62),
			new ("Aimer", "Pets > DPS", "Drippy Radiant Champion Channels Ancient Kobold", 49),
			new ("Air Plane", "Pets > DPS", "Goated Cooked Sentinel Withstands Drippy Dragon", 126),
			new ("Aladdins Wish", "Weapons > Huntress", "Mid Locked Trap Builds Hardened Beast", 48),
			new ("Alpha", "Pets > Exclusives", "Enchanted Swift Obelisk Wipes Hardened Raider", 796),
			new ("aMAZEing Vision", "Accessories > Masks", "Wild Swift Champion Deletes Juicy Pillager", 62),
			new ("Amor 14k", "Pets > Collectibles", "Swift Mid Apprentice Smashes Luminous Beast", 76),
			new ("Amor 21k", "Pets > Collectibles", "Fragile Tilted Banner Withstands Enchanted Ogre", 85),
			new ("Amplifiers", "Accessories > Mid End Bracers", "Grim Drippy Lightning Fortifies Luminous Raider", 210),
			new ("Ancient Plume", "Accessories > Mid End Hats", "Tilted Heroic Core Summons Tilted Brute", 99),
			new ("Aphiry", "Pets > Streamer", "Cracked Buffed Monk Smashes Shiny Brute", 78),
			new ("Armguard of Deforestation", "Accessories > Bracers", "Fire Ancient Protector Launches Heroic Orc", 81),
			new ("Armguard of Earth", "Accessories > Bracers", "Radiant Drippy Squire Locks Juicy Demon", 78),
			new ("Armguard of Fire", "Accessories > Bracers", "Corrupted Sweaty Protector Defends Tactical Raider", 82),
			new ("Armguard of Hate", "Accessories > Bracers", "Juicy Swift Monk Defends Ancient Invader", 82),
			new ("Armguard of Lightning", "Accessories > Bracers", "Mid Brutal Beacon Yeets Nerfed Marauder", 89),
			new ("Armguard of Love", "Accessories > Bracers", "Mid Corrupted Beacon Channels Mythic Fiend", 84),
			new ("Armguard of Poison", "Accessories > Bracers", "Chaotic Sweaty Builder Ratios Swift Destroyer", 82),
			new ("Armguard of Radiation", "Accessories > Bracers", "Drippy Swift Guardian Pops Luminous Swarm", 84),
			new ("Armguard of Smog", "Accessories > Bracers", "Beloved Luminous Totem Fortifies Tactical Warlock", 85),
			new ("Armguard of Toxic Waste", "Accessories > Bracers", "Mid Fortified Banner Builds Goated Wyvern", 78),
			new ("Azure Peak", "Accessories > Mid End Hats", "Endless Locked Beacon Defends Swift Spider", 93),
			new ("Ball Blaster", "Weapons > Monk", "Chaotic Corrupted Monk Repairs Tactical Corruptor", 77),
			new ("Ball Blaster", "Weapons > Monk", "Ancient Beloved Monk Repairs Tilted Corruptor", 77),
			new ("Battlecruiser Debris Mask", "Accessories > Masks", "Ancient Corrupted Huntress Freezes Ancient Abomination", 51),
			new ("Bean's Leftovers", "Accessories > Masks", "Corrupted Mythic Lightning Builds Mythic Ravager", 44),
			new ("Black Mage", "Pets > Exclusives", "Tilted Mid Champion Summons Ancient Warlock", 600),
			new ("bLACK mAGICK", "Pets > DPS", "Shattered Locked Warden Camps Luminous Spider", 95),
			new ("Black Satin Peak", "Accessories > Mid End Hats", "Beloved Shiny Guardian Channels Shattered Brood", 58),
			new ("Black Shades", "Accessories > High End Masks", "Shattered Fragile Banner Shatters Hardened Brood", 895),
			new ("Black Shades", "Accessories > High End Masks", "Tilted Mid Relic Locks Juicy Orc", 895), 
			new ("Black Shades", "Accessories > High End Masks", "Fortified Brutal Monk Repairs Corrupted Beast", 895),
			new ("Black Shades", "Accessories > High End Masks", "Cracked Endless Stronghold Builds Brutal Corruptor", 895),
			new ("Black Shades", "Accessories > High End Masks", "Sweaty Cooked Core Carries Hardened Assassin", 895),
			new ("Black Shades", "Accessories > High End Masks", "Grim Wild Totem Repairs Swift Berserker", 895), 
			new ("Black Shades", "Accessories > High End Masks", "Goated Corrupted Totem Shatters Mythic Horde", 895),
			new ("Black Shades", "Accessories > High End Masks", "Chaotic Tilted Trap Spams Fragile Warlock", 895),
			new ("Black Shades", "Accessories > High End Masks", "Locked Fire Defender Pops Enchanted Horde", 895),
			new ("Black Shades", "Accessories > High End Masks", "Luminous Drippy Protector Farms Radiant Beast", 895),
			new ("Black Shades", "Accessories > High End Masks", "Chaotic Cracked Tower Withstands Shiny Assassin", 895),
			new ("Black Shades", "Accessories > High End Masks", "Drippy Wild Core Throws Heroic Invader", 895),
			new ("Black Shades", "Accessories > High End Masks", "Swift Fortified Armory Camps Grim Raider", 895),
			new ("Black Shades", "Accessories > High End Masks", "Nerfed Grim Harpoon Repels Fire Spider", 895),
			new ("Black Shades", "Accessories > High End Masks", "Tactical Sweaty Relic Pops Wild Demon", 895),
			new ("Black Shades", "Accessories > High End Masks", "Cooked Shiny Guardian Summons Tactical Ravager", 895),
			new ("Black Shades", "Accessories > High End Masks", "Heroic Chaotic Trap Shocks Fire Wretch", 895), // you are speed
			new ("Black Shades", "Accessories > High End Masks", "Fortified Nerfed Forge Locks Sweaty Spider", 895), // from DWHU
			new ("Blahaj", "Pets > DPS", "Nerfed Fire Sigil Pops Cooked Brood", 272),
			new ("Blessed Brownie", "Pets > Exclusives", "Grim Hardened Barricade Freezes Luminous Ogre", 985),
			new ("Bling! Bling! Bracers", "Accessories > Bracers", "Juicy Locked Defender Builds Chaotic Wyvern", 58),
			new ("Blu", "Pets > Collectibles", "Beloved Ancient Fireball Repels Juicy Overlord", 51),
			new ("Blu", "Pets > Collectibles", "Fortified Heroic Relic Deletes Locked Necromancer", 51),
			new ("Blueberry", "Pets > Guardians", "Radiant Nerfed Shiro Withstands Wild Brood", 221),
			new ("Bones", "Pets > Exclusives", "Fortified Cooked Monk Breaches Juicy Wyvern", 298),
			new ("Boneyard Blade", "Weapons > Squire", "Juicy Chaotic Squire Defends Cooked Kobold", 50),
			new ("Boneyard Blade", "Weapons > Squire", "Tilted Mythic Workshop Shatters Brutal Wretch", 50),
			new ("Broken Heart", "Pets > Exclusives", "Drippy Grim Tower Shocks Juicy Pillager", 3987),
			new ("Butterscotch", "Pets > Exclusives", "Swift Wild Harpoon Locks Luminous Brood", 3440),
			new ("Captain Djinn's Hat", "Accessories > Hats", "Luminous Beloved Huntress Camps Hardened Invader", 56),
			new ("Captain Isom", "Pets > Collectibles", "Fire Shiny Tower Wins Shattered Brute", 124),
			new ("Carapace of the Queen", "Accessories > Shields", "Swift Swift Shiro Wipes Swift Necromancer", 62),
			new ("Care Bear 300/1", "Unknown","Shattered Locked Defender Camps Shattered Ogre", 1200),
			new ("Care Bear", "Pets > Collectibles", "Endless Nerfed Warden Repairs Goated Raider", 83),
			new ("Celebracers", "Accessories > High End Bracers", "Shattered Enchanted Apprentice Pops Cracked Kobold", 412),
			new ("Celebration", "Accessories > High End Hats", "Grim Buffed Shiro Snowballs Nerfed Goblin", 633),
			new ("Cheshire", "Pets > Exclusives", "Buffed Drippy Totem Shatters Juicy Necromancer", 2875),
			new ("Chicken Lover 3000", "Weapons > Monk", "Shattered Endless Champion Boosts Chaotic Ogre", 47),
			new ("Chocolate Wafer Roll", "Weapons > Monk", "Goated Goated Armory Shatters Chaotic Wretch", 123),
			new ("Christmas Nesso", "Pets > DPS", "Fragile Enchanted Lightning Repairs Mid Corruptor", 195), // tigi
			new ("Church", "Pets > DPS", "Radiant Fragile Stronghold Shatters Chaotic Raider", 225),			
			new ("Cinnabar", "Pets > Collectibles", "Sweaty Tactical Totem Ratios Corrupted Fiend", 69),
			new ("Cinnamon", "Pets > Guardians", "Chaotic Swift Workshop Breaches Shattered Raider", 188),
			new ("Cloud Bracers", "Accessories > High End Bracers", "Mythic Fragile Sentinel Freezes Luminous Ogre", 342),
			new ("Clood", "Pets > Collectibles", "Mythic Nerfed Tower Summons Shiny Horde", 183),			
			new ("Cobra's Whisper", "Weapons > Apprentice", "Mid Grim Shiro Fortifies Ancient Horde", 110),
			new ("Copper Egg", "Pets > Builder", "Goated Buffed Huntress Locks Tilted Invader", 224),
			new ("Crimson", "Weapons > Squire", "Enchanted Hardened Barricade Shocks Swift Destroyer", 55),		
			new ("Cursed Brownie", "Pets > Collectibles", "Cracked Endless Relic Carries Wild Warlock", 91),
			new ("Darkling", "Pets > Streamer", "Nerfed Shattered Forge Yeets Drippy Wyvern", 101),
			new ("Death By Soda", "Weapons > Huntress", "Nerfed Beloved Stronghold Boosts Locked Shaman", 130),
			new ("Death Wish", "Weapons > Huntress", "Chaotic Beloved Warden Wipes Goated Fiend", 47),
			new ("Definitely A Berry", "Weapons > Apprentice", "Tilted Juicy Obelisk Camps Mythic Ogre", 56),
			new ("Delver's Bracers", "Accessories > High End Bracers", "Mythic Beloved Banner Freezes Fortified Raider", 652),
			new ("Delver's Bracers", "Accessories > High End Bracers", "Fortified Mythic Fireball Builds Hardened Demon", 652),
			new ("Delver's Brooch", "Accessories > High End Hats", "Juicy Mythic Huntress Camps Cooked Ogre", 832),
			new ("Delver's Eyewear", "Accessories > High End Masks", "Mid Fortified Lightning Deletes Hardened Orc", 779),
			new ("Delver's Eyewear", "Accessories > High End Masks", "Swift Fortified Core Locks Fortified Shaman", 779), // updated
			new ("Dragon of the North", "Accessories > Bracers", "Sweaty Heroic Huntress Repels Hardened Fiend", 58),
			new ("Dunce Cap", "Accessories > Mid End Hats", "Goated Radiant Barricade Wins Brutal Minion", 78),
			new ("Dunce Cap", "Accessories > Mid End Hats","Hardened Luminous Barricade Wins Drippy Minion", 78),
			new ("Dwarven Miners Mask", "Accessories > Masks", "Locked Endless Barricade Channels Enchanted Ravager", 43),
			new ("Egg (Blue)", "Pets > Builder", "Chaotic Fragile Sigil Snowballs Enchanted Wyvern", 137),
			new ("Egg (Red)", "Pets > Builder", "Shiny Tilted Beacon Launches Tactical Pack", 148),
			new ("Egg (Green)", "Pets > Builder", "Radiant Grim Armory Rushes Locked Minion", 166),
			new ("Egg (Yellow)", "Pets > Builder", "Chaotic Tactical Core Launches Wild Pillager", 182),
			new ("Electric Peak", "Accessories > Exclusives", "Sweaty Juicy Relic Spams Luminous Minion", 328),
			new ("Elf Party Hat", "Accessories > High End Hats", "Nerfed Heroic Harpoon Throws Enchanted Dragon", 650),
			new ("Eternity", "Accessories > Mid End Bracers", "Cooked Nerfed Stronghold Repels Hardened Ogre", 83),
			new ("Excarlibug", "Weapons > Apprentice", "Juicy Tactical Protector Fortifies Swift Invader", 52),
			new ("Expanders", "Accessories > Mid End Hats", "Chaotic Fortified Stronghold Smashes Heroic Marauder", 92),
			new ("Face of RNG", "Accessories > Masks", "Mid Beloved Protector Repairs Tactical Minion", 60),
			new ("Fairy Floss on Rocks", "Accessories > Mid End Bracers", "Cracked Grim Core Rushes Beloved Abomination", 88),
			new ("Falcor", "Pets > Collectibles", "Buffed Buffed Obelisk Freezes Fragile Raider", 74),
			new ("Fallen Bark", "Accessories > Mid End Bracers", "Drippy Radiant Fireball Throws Swift Spider", 55),
			new ("Fearsome Trainer Mask", "Accessories > Masks", "Chaotic Swift Totem Explodes Radiant Spider", 45),
			new ("Feathers of the Sky", "Accessories > Mid End Hats", "Tactical Drippy Trap Channels Radiant Goblin", 68),
			new ("Final Patch", "Accessories > High End Masks", "Radiant Endless Harpoon Snowballs Juicy Pack", 524),
			new ("Final Patch", "Accessories > High End Masks", "Fortified Wild Relic Wins Wild Wretch", 524),
			new ("Fire Balloon", "Pets > DPS", "Juicy Endless Aura Shatters Locked Ogre", 161),
			new ("Firestorm", "Weapons > Huntress", "Wild Fragile Vanguard Burns Cracked Ogre", 63),
			new ("First Contact", "Weapons > Monk", "Shiny Wild Relic Boosts Shiny Overlord", 72),
			new ("Furious George", "Pets > Collectibles", "Corrupted Corrupted Shiro Shatters Radiant Assassin", 49),
			new ("Gaia's Last Gift", "Weapons > Huntress", "Buffed Wild Crystal Defends Tactical Wyvern", 156),
			new ("Gaia's Last Gift", "Weapons > Huntress", "Heroic Endless Vanguard Launches Heroic Wyvern", 156),
			new ("Gamma", "Pets > Exclusives", "Mythic Wild Tower Wipes Drippy Goblin", 771),
			new ("Genie King's Prized Jewel", "Accessories > Hats", "Fire Sweaty Lightning Freezes Beloved Ravager", 59),
			new ("Ginger", "Pets > Guardians", "Shiny Swift Harpoon Camps Heroic Goblin", 285),
			new ("Glaciers Demise", "Weapons > Squire", "Swift Beloved Defender Burns Luminous Horde", 269),
			new ("GMO Giraffe", "Pets > Builder", "Goated Radiant Guardian Builds Fortified Ravager", 112),
			new ("Golden Egg", "Pets > Builder", "Endless Luminous Tower Wipes Endless Cultist", 248),
			new ("Golden Roost", "Weapons > Huntress", "Cracked Fragile Huntress Launches Locked Swarm", 54),
			new ("Golden Shroom", "Pets > Collectibles", "Sweaty Fire Sentinel Locks Cooked Invader", 89),
			new ("Golden Wood Shield", "Accessories > Shields", "Shiny Swift Banner Withstands Brutal Ogre", 159),
			new ("Goron Tunic", "Accessories > Armor Pieces", "Corrupted Juicy Obelisk Builds Tilted Warlock", 68),
			new ("Grapes", "Pets > Guardians", "Brutal Shiny Beacon Freezes Buffed Invader", 241),
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Goated Buffed Relic Pops Hardened Marauder", 3050),
			new ("Greater Magicite of Love", "Pets > Exclusives", "Shattered Endless Huntress Breaches Sweaty Swarm", 12800),
			new ("Greater Magicite of Pumpkin", "Pets > Builder", "Cracked Cooked Beacon Wipes Buffed Ogre", 387),
			new ("Greater Magicite of the Rainbow", "Pets > Builder", "Brutal Tilted Trap Freezes Ancient Spider", 347),
			new ("Greater Magicite of the Water", "Pets > Exclusives", "Chaotic Corrupted Sigil Wins Hardened Goblin", 20249),
			new ("Greater Magicite of the Wind", "Pets > Builder", "Chaotic Swift Warden Rushes Tactical Berserker", 371),
			new ("Grinch's #1 Fan", "Pets > Collectibles", "Fortified Mid Vanguard Freezes Mid Destroyer", 41),
			new ("Groovy Mask", "Accessories > Masks", "Cooked Mid Warden Repairs Juicy Wretch", 60),
			new ("Gummy Worm", "Weapons > Exclusive", "Mid Sweaty Monk Farms Juicy Invader", 220),
			new ("Honor Sword", "Weapons > Exclusive", "Drippy Tilted Champion Channels Brutal Raider", 813), // 100
			new ("Honor Sword", "Weapons > Exclusive", "Grim Buffed Armory Repairs Fragile Fiend", 813), // 200
			new ("Honor Sword", "Weapons > Exclusive", "Shiny Mid Guardian Throws Mythic Wretch", 813), // 300
			new ("Honor Sword", "Weapons > Exclusive", "Tilted Beloved Builder Builds Radiant Pack", 813), // 400			
			new ("Hot Air Balloon", "Pets > Exclusives", "Cracked Shattered Stronghold Burns Cooked Demon", 507),
			new ("Howling Werewolf", "Weapons > Huntress", "Beloved Tilted Builder Pops Enchanted Pillager", 54),
			new ("Howling Werewolf", "Weapons > Huntress", "Tactical Cracked Warden Camps Fragile Goblin", 54),
			new ("Inkzooka", "Weapons > Huntress", "Endless Heroic Defender Repairs Buffed Corruptor", 57),
			new ("Iratxo", "Pets > Collectibles", "Juicy Corrupted Trap Carries Drippy Destroyer", 87),
			new ("Jack in The Box", "Pets > DPS", "Wild Mid Barricade Explodes Enchanted Marauder", 227),
			new ("Jason Vorhees Mask", "Accessories > Masks", "Juicy Cracked Forge Yeets Fire Destroyer", 47),
			new ("Juicy Fruit", "Pets > Streamer", "Fire Nerfed Lightning Shocks Tactical Cultist", 217),
			new ("Kraken's Good Eye", "Accessories > Masks", "Tactical Ancient Sigil Shatters Mid Necromancer", 50),
			new ("Krampus Hat", "Accessories > Exclusives", "Fortified Cooked Monk Snowballs Cracked Raider", 483),
			new ("Lava cuffs", "Accessories > Bracers", "Mythic Grim Obelisk Spams Mid Warlock", 57),
			new ("Lava Dancer Mask", "Accessories > Masks", "Shiny Enchanted Sigil Deletes Shiny Goblin", 52),
			new ("Lettuce", "Pets > DPS", "Brutal Juicy Core Wipes Juicy Invader", 57),
			new ("Liebe", "Pets > Exclusives", "Beloved Fragile Beacon Yeets Brutal Minion", 354),
			new ("Lieutenant Sparkles", "Pets > Collectibles", "Luminous Brutal Guardian Wins Cooked Swarm", 90),
			new ("Lime Pie", "Pets > Guardians", "Endless Tilted Guardian Breaches Juicy Brood", 217),
			new ("Limetori", "Pets > Exclusives", "Endless Locked Workshop Camps Luminous Cultist", 2700),
			new ("Lover's Shackles", "Accessories > Mid End Bracers", "Fire Endless Champion Burns Mid Horde", 260),
			new ("Lover's Shackles", "Accessories > Mid End Bracers", "Locked Shattered Harpoon Farms Endless Wretch", 260), // kay
			new ("Lumen", "Weapons > Huntress", "Beloved Goated Apprentice Summons Locked Invader", 57),
			new ("Lunar Demon", "Weapons > Apprentice", "Beloved Grim Apprentice Boosts Beloved Goblin", 62),
			new ("Lunar Magic", "Weapons > Apprentice", "Swift Fire Aura Rushes Cooked Warlock", 52),
			new ("Mad Joe", "Pets > Collectibles", "Luminous Tilted Fireball Freezes Cooked Minion", 63),
			new ("Maelstrom", "Weapons > Apprentice", "Hardened Mid Lightning Shatters Nerfed Berserker", 63),
			new ("Magnificators", "Accessories > Mid End Masks", "Goated Ancient Fireball Builds Tactical Dragon", 113),
			new ("Magora's Mask", "Accessories > Masks", "Shiny Radiant Warden Clutches Tilted Orc", 51),
			new ("Malory", "Pets > Exclusives", "Goated Drippy Relic Boosts Fortified Spider", 848),
			new ("Malory", "Pets > Exclusives", "Locked Drippy Fireball Defends Ancient Berserker", 848),
			new ("Malory", "Pets > Exclusives", "Mythic Cracked Forge Repairs Luminous Marauder", 848),
			new ("Mana Master", "Pets > Collectibles", "Juicy Swift Lightning Ratios Heroic Cultist", 62),
			new ("Marid", "Pets > Builder", "Buffed Radiant Stronghold Wins Goated Invader", 43),
			new ("Mars", "Pets > Builder", "Mid Fortified Protector Snowballs Mid Abomination", 58),
			new ("Mask of Legends", "Accessories > Mid End Masks", "Fire Heroic Harpoon Shatters Shattered Spider", 92),
			new ("Mask of the Pumpkin King", "Accessories > Mid End Masks", "Shiny Drippy Sentinel Locks Brutal Horde", 56),
			new ("Memoriam", "Accessories > Mid End Bracers", "Ancient Cooked Champion Launches Shiny Warlock", 98),
			new ("Mezcal", "Pets > Streamer", "Fire Cracked Aura Wipes Fortified Pack", 150),
			new ("Mike", "Pets > Exclusives", "Locked Brutal Defender Builds Grim Ravager", 8766),
			new ("Mining Etheria in search of vast wealth", "Unknown","Fire Fragile Squire Spams Hardened Assassin", 767),
			new ("Minish Hat", "Accessories > Armor Pieces", "Shattered Heroic Sentinel Carries Luminous Cultist", 48),
			new ("Misri", "Accessories > Mid End Hats", "Grim Chaotic Apprentice Spams Nerfed Orc", 68),
			new ("Molon Labe", "Accessories > Exclusives", "Locked Tilted Builder Camps Shiny Pack", 353),
			new ("Molon Labe", "Accessories > Exclusives", "Cooked Beloved Core Rushes Hardened Pillager", 353),
			new ("Molon Labe", "Accessories > Exclusives", "Luminous Chaotic Sigil Withstands Corrupted Corruptor", 353), // tigi
			new ("Moraggo's Secret Treasure", "Weapons > Monk", "Luminous Swift Guardian Farms Beloved Destroyer", 74),
			new ("Mr Bed", "Pets > Exclusives", "Tilted Tactical Relic Smashes Hardened Demon", 1677),
			new ("Mr Crackers", "Pets > DPS", "Enchanted Radiant Sentinel Repairs Buffed Raider", 384),
			new ("Mr Crackers", "Pets > DPS", "Ancient Wild Protector Farms Fire Warlock", 384),
			new ("Mr Skelly", "Pets > Builder", "Locked Luminous Relic Deletes Drippy Assassin", 61),
			new ("Munchkin", "Pets > DPS", "Mid Wild Beacon Clutches Wild Orc", 112),
			new ("Mustard", "Pets > Guardians", "Corrupted Locked Guardian Spams Drippy Pillager", 167),
			new ("Mutated Hand", "Weapons > Squire", "Enchanted Beloved Fireball Carries Heroic Ravager", 50),
			new ("Natori", "Pets > DPS", "Nerfed Buffed Forge Repairs Mythic Ogre", 260),
			new ("Neptune", "Pets > Builder", "Shattered Enchanted Banner Explodes Chaotic Raider", 127),
			new ("New Patch Celebration", "Accessories > High End Hats", "Drippy Heroic Barricade Boosts Tactical Brute", 669),
			new ("Obunga's Other Half", "Pets > Streamer", "Chaotic Shattered Stronghold Locks Ancient Overlord", 73),
			new ("Ocean", "Accessories > Mid End Masks", "Buffed Shattered Tower Burns Luminous Spider", 67),
			new ("Ocean", "Accessories > Mid End Masks", "Buffed Hardened Squire Launches Chaotic Wretch", 67),
			new ("Odin's Mask", "Accessories > Masks", "Sweaty Chaotic Obelisk Breaches Shattered Invader", 46),
			new ("Olaf", "Pets > Exclusives", "Corrupted Mid Armory Wipes Ancient Swarm", 471),
			new ("Old One's Stache", "Accessories > Masks", "Wild Grim Banner Builds Ancient Spider", 45),
			new ("Old One's Stache", "Accessories > Masks", "Cracked Buffed Huntress Shocks Beloved Raider", 45), // kay			
			new ("Ork Hat", "Accessories > High End Hats", "Fire Corrupted Monk Boosts Brutal Swarm", 1215),// akatiki/rl/old school/1
			new ("Ork Hat", "Accessories > High End Hats", "Nerfed Fragile Workshop Shatters Chaotic Cultist", 1215), // akatiki/rl/old school/2			
			new ("Ork Hat", "Accessories > High End Hats", "Shiny Nerfed Defender Farms Locked Pack", 1215), // akatiki/rl/normal/1
			new ("Ork Hat", "Accessories > High End Hats", "Radiant Tilted Obelisk Breaches Cooked Orc", 1215), // akatiki/rl/normal/2			
			new ("Ork Hat", "Accessories > High End Hats", "Mythic Swift Trap Deletes Enchanted Assassin", 1215), // akatiki/rl/hard/1
			new ("Ork Hat", "Accessories > High End Hats", "Heroic Grim Protector Locks Nerfed Spider", 1215), // akatiki/rl/hard/2
			new ("Ork Hat", "Accessories > High End Hats", "Chaotic Ancient Huntress Carries Wild Goblin", 1215), // akatiki/rl/extreme/1
			new ("Ork Hat", "Accessories > High End Hats", "Nerfed Juicy Aura Ratios Beloved Necromancer", 1215), // akatiki/rl/extreme/2
			new ("Ork Hat", "Accessories > High End Hats", "Drippy Juicy Monk Fortifies Swift Kobold", 1215), // non-exclusive
			new ("Ork Hat", "Accessories > High End Hats", "Mythic Grim Beacon Freezes Ancient Wretch", 1215),// akatiki/nm/old school/1
			new ("Ork Hat", "Accessories > High End Hats", "Enchanted Swift Builder Withstands Shiny Minion", 1215),// akatiki/nm/old school/2
			new ("Ork Hat", "Accessories > High End Hats", "Beloved Nerfed Crystal Fortifies Mid Spider", 1215),// akatiki/nm/normal/1
			new ("Ork Hat", "Accessories > High End Hats", "Enchanted Chaotic Fireball Launches Endless Ravager", 1215),// akatiki/nm/normal/2		
			new ("Ork Hat", "Accessories > High End Hats", "Radiant Swift Aura Yeets Ancient Brood", 1215),// akatiki/nm/hard/1
			new ("Ork Hat", "Accessories > High End Hats", "Chaotic Cracked Fireball Pops Radiant Berserker", 1215),// akatiki/nm/hard/2
			new ("Ork Hat", "Accessories > High End Hats", "Sweaty Tilted Lightning Rushes Beloved Brood", 1215), // akatiki/nm/extreme/1
			new ("Ork Hat", "Accessories > High End Hats", "Mythic Corrupted Relic Locks Luminous Horde", 1215), // akatiki/nm/extreme/2
			new ("Ork Hat", "Accessories > High End Hats", "Corrupted Beloved Vanguard Carries Swift Minion", 1215), // akatiki/nm/extreme/3
			new ("Overload", "Pets > Builder", "Chaotic Goated Core Carries Luminous Pillager", 155),
			new ("Overlord", "Pets > Streamer", "Heroic Mid Stronghold Shatters Ancient Kobold", 120),
			new ("Paper Straw", "Weapons > Exclusive", "Beloved Nerfed Huntress Wins Sweaty Necromancer", 233),
			new ("Party Horn", "Accessories > Mid End Masks", "Heroic Mid Relic Freezes Fortified Invader", 67),
			new ("PB&J", "Pets > Exclusives", "Beloved Cracked Totem Yeets Nerfed Minion", 907),
			new ("Pegasus Boots", "Accessories > Armor Pieces", "Hardened Enchanted Defender Launches Shiny Kobold", 46),
			new ("Personal Resort", "Pets > Streamer", "Brutal Luminous Warden Spams Mid Fiend", 275),
			new ("Personal Resort", "Pets > Streamer",  "Hardened Nerfed Lightning Boosts Mid Ogre", 275),
			new ("Phrosty", "Pets > Streamer", "Locked Shattered Core Camps Shiny Raider", 26),
			new ("Pixel Seahorse", "Pets > Exclusive", "Endless Corrupted Squire Wipes Goated Demon", 0), // Kay?			
			new ("Ploutonion", "Accessories > Shields", "Ancient Radiant Champion Fortifies Swift Ogre", 191),
			new ("Plum", "Pets > DPS", "Locked Buffed Stronghold Deletes Juicy Pillager", 555),
			new ("Pole of the North Star", "Weapons > Exclusive", "Mid Enchanted Monk Camps Cracked Invader", 1250),
			new ("Pole of the South Star", "Weapons > Apprentice", "Sweaty Buffed Barricade Clutches Shattered Berserker", 119),
			new ("Poptart", "Pets > DPS", "Buffed Drippy Builder Defends Ancient Cultist", 260),
			new ("Poseidon's Shorebreaker", "Weapons > Monk", "Nerfed Tilted Guardian Shatters Tactical Fiend", 123),
			new ("Power Gauntlets", "Accessories > Armor Pieces", "Hardened Beloved Banner Deletes Fortified Ogre", 55),
			new ("Pride of the Kraken", "Weapons > Huntress","Goated Brutal Vanguard Explodes Heroic Spider", 43),
			new ("Proto VPC", "Accessories > Exclusives","Brutal Beloved Shiro Fortifies Corrupted Wyvern", 10000),
			new ("Pumpkin Head Celebration", "Accessories > High End Hats", "Locked Ancient Workshop Camps Tilted Marauder", 651),
			new ("Pumpkin Peak", "Accessories > Mid End Hats", "Luminous Locked Beacon Carries Wild Destroyer", 59),
			new ("Queen Georgia", "Pets > DPS", "Drippy Endless Fireball Withstands Beloved Fiend", 69),
			new ("Raspberry Staff", "Weapons > Exclusive", "Wild Corrupted Defender Burns Fire Shaman", 488),
			new ("Red", "Pets > DPS", "Goated Corrupted Barricade Yeets Tilted Pillager", 58),
			new ("Retinazer", "Pets > DPS", "Cooked Mid Squire Builds Fire Kobold", 310),
			new ("Rock's Feather", "Accessories > Hats", "Heroic Goated Beacon Shatters Heroic Raider", 53),
			new ("Rockshatter", "Weapons > Huntress", "Drippy Hardened Sigil Repels Luminous Wyvern", 108),
			new ("Rosemary", "Pets > Streamer", "Drippy Wild Shiro Boosts Endless Brute", 253),
			new ("Sahara", "Weapons > Apprentice", "Buffed Tilted Sigil Camps Tilted Destroyer", 53),
			new ("Salem", "Pets > DPS", "Swift Fortified Squire Farms Fortified Warlock", 71),
			new ("Sandstone Shield", "Accessories > Shields", "Fire Mythic Builder Clutches Juicy Ravager", 325), // added 2-19-2026
			new ("Santa's Spare Hat", "Accessories > Mid End Hats", "Drippy Heroic Protector Spams Buffed Wyvern", 71),
			new ("Sapphire", "Weapons > Squire", "Hardened Shiny Relic Explodes Fire Swarm", 58),
			new ("Serpent of the North", "Pets > DPS", "Brutal Hardened Lightning Withstands Beloved Corruptor", 62),
			new ("Shield of Mirrors", "Accessories > Shields", "Beloved Brutal Totem Boosts Locked Warlock", 54),
			new ("Shadow Bringer", "Weapons > Exclusive", "Nerfed Enchanted Armory Ratios Goated Ravager", 285),
			new ("Silver Egg", "Pets > Builder", "Shiny Sweaty Protector Repels Fortified Wretch", 211),
			new ("Skittles (Blue)", "Pets > DPS","Luminous Fire Forge Rushes Hardened Necromancer", 48),
			new ("Skittles (Green)", "Pets > DPS","Shattered Ancient Huntress Builds Fragile Pack", 48),
			new ("Skittles (Orange)", "Pets > DPS","Luminous Endless Defender Launches Tilted Pillager", 43),
			new ("Skittles (Pink)", "Pets > DPS","Shattered Fire Lightning Throws Fortified Berserker", 61),
			new ("Skittles (Purple)", "Pets > DPS","Sweaty Drippy Harpoon Snowballs Fragile Pillager", 49),
			new ("Skittles (Red)", "Pets > DPS","Luminous Sweaty Fireball Locks Endless Horde", 49),
			new ("Skittles (Yellow)", "Pets > DPS","Grim Mythic Forge Channels Cooked Warlock", 56),
			new ("Snowballer 3000", "Weapons > Huntress", "Drippy Locked Totem Wipes Fire Corruptor", 36),
			new ("Something Blue", "Accessories > Hats", "Fortified Radiant Forge Defends Mid Berserker", 61),
			new ("Something Coral", "Accessories > Hats", "Tilted Shiny Protector Explodes Ancient Beast", 49),
			new ("Something Crimson", "Accessories > Hats", "Heroic Tilted Fireball Spams Fortified Assassin", 48),
			new ("Something Fuschia", "Accessories > Hats", "Cracked Brutal Stronghold Builds Sweaty Orc", 48),
			new ("Something Green", "Accessories > Hats", "Fire Juicy Tower Spams Sweaty Pillager", 48),
			new ("Something Lemon", "Accessories > Hats", "Tilted Beloved Protector Boosts Beloved Dragon", 48),
			new ("Something Lime", "Accessories > Hats", "Shiny Nerfed Huntress Snowballs Mythic Warlock", 48),
			new ("Something Navy", "Accessories > Hats", "Shiny Juicy Sentinel Defends Mythic Brute", 67),
			new ("Something Orange", "Accessories > Hats", "Wild Endless Champion Defends Wild Fiend", 56),
			new ("Something Pink", "Accessories > Exclusives", "Tactical Fortified Stronghold Shatters Swift Pillager", 1295),
			new ("Something Pink", "Accessories > Exclusives", "Fire Fire Trap Clutches Enchanted Destroyer", 1295),
			new ("Something Purple", "Accessories > Hats", "Beloved Tilted Champion Repels Fragile Orc", 45),
			new ("Something Red", "Accessories > Hats", "Drippy Chaotic Guardian Defends Radiant Kobold", 59),
			new ("Something Violet", "Accessories > Hats", "Goated Shattered Defender Smashes Drippy Marauder", 49),
			new ("Something Yellow", "Accessories > Hats", "Luminous Brutal Forge Clutches Beloved Overlord", 48),
			new ("Spartan Shield", "Accessories > Shields", "Fortified Drippy Monk Explodes Drippy Pillager", 125),
			new ("Spartan Shield", "Accessories > Shields",  "Fragile Ancient Harpoon Repels Corrupted Abomination", 125),
			new ("Spartan Shield", "Accessories > Shields",  "Chaotic Mythic Forge Repels Enchanted Wyvern", 125),
			new ("Spartan Spear", "Weapons > Monk", "Wild Cracked Apprentice Deletes Radiant Swarm", 110),
			new ("Spazmatism", "Pets > DPS", "Endless Fragile Crystal Clutches Sweaty Warlock", 390),
			new ("Spearmint", "Weapons > Monk", "Locked Luminous Builder Wipes Tactical Orc", 52),
			new ("Speed Freak Feather", "Accessories > Hats", "Ancient Endless Guardian Clutches Brutal Swarm", 47),
			new ("Speedster", "Pets > Collectibles", "Endless Grim Tower Summons Hardened Demon", 63),
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Cooked Ancient Squire Deletes Juicy Wyvern", 883),         
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Chaotic Hardened Totem Explodes Locked Abomination", 883), // Fastest
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Goated Hardened Beacon Clutches Chaotic Marauder", 883), // Mistymire
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Juicy Beloved Forge Ratios Shiny Horde", 883), // Aquanos
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Shattered Juicy Tower Spams Fire Corruptor", 883), // Sky City
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Juicy Goated Sigil Shocks Brutal Raider", 883), // Crystalline Dimension
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Corrupted Heroic Banner Smashes Grim Ravager", 883), // Moraggo		
			new ("Speedy", "Pets > DPS", "Enchanted Brutal Armory Breaches Wild Pillager", 48),
			new ("Splash Ops", "Weapons > Huntress", "Mid Grim Monk Shocks Goated Shaman", 56),
			new ("Spoony lvl 100", "Weapons > Exclusive", "Wild Buffed Apprentice Repels Mid Ravager", 1400),
			new ("Staff of the Pumpkin King", "Weapons > Apprentice", "Cracked Chaotic Sentinel Rushes Sweaty Assassin", 57),
			new ("Staff of the Pumpkin King", "Weapons > Apprentice", "Endless Hardened Banner Shatters Enchanted Warlock", 57),
			new ("Stieglitz", "Pets > Collectibles", "Hardened Tactical Protector Shatters Heroic Beast", 137),
			new ("Strawberry Rock", "Pets > Collectibles", "Juicy Beloved Guardian Defends Tactical Overlord", 147),
			new ("Strawberry", "Pets > Guardians", "Corrupted Corrupted Lightning Breaches Fortified Necromancer", 230),
			new ("Strawberry Wafer Roll", "Weapons > Monk", "Sweaty Tilted Forge Ratios Hardened Cultist", 110),
			new ("Sun Staff", "Weapons > Streamer", "Fire Cooked Obelisk Builds Chaotic Necromancer", 360),
			new ("Sun Staff", "Weapons > Streamer", "Chaotic Endless Stronghold Builds Ancient Kobold", 360),
			new ("Sword of Valor (Blue)", "Weapons > Squire","Mythic Shiny Aura Locks Beloved Destroyer", 52),
			new ("Sword of Valor (Green)", "Weapons > Squire","Goated Heroic Shiro Breaches Hardened Invader", 52),
			new ("Sword of Valor (Red)", "Weapons > Squire","Radiant Wild Obelisk Pops Swift Beast", 52),
			new ("Sword of Valor (Yellow)", "Weapons > Squire","Swift Corrupted Apprentice Repels Wild Warlock", 60),
			new ("Tabula Rasa", "Accessories > Exclusive Armor Pieces", "Drippy Beloved Relic Boosts Heroic Wyvern", 253),
			new ("Talay's Doom", "Weapons > Squire", "Tilted Wild Barricade Breaches Goated Invader", 105),
			new ("Terra's Magicite Brooch", "Accessories > Hats", "Goated Tactical Banner Boosts Swift Spider", 43),
			new ("Templar Shield", "Accessories > Shields", "Swift Goated Builder Deletes Mythic Wyvern", 300),
			new ("Tess", "Pets > Exclusives", "Juicy Buffed Beacon Throws Tactical Ogre", 664),
			new ("The Aristocrat's Gaze", "Accessories > High End Masks", "Enchanted Juicy Fireball Ratios Brutal Ogre", 585),
			new ("The Cavalry", "Pets > DPS", "Swift Buffed Trap Wins Ancient Ravager", 71),
			new ("The Cavalry", "Pets > DPS", "Sweaty Mythic Obelisk Wipes Heroic Swarm", 71),
			new ("The Devil's Poolskimmer", "Weapons > Monk", "Luminous Swift Obelisk Explodes Endless Ravager", 54),
			new ("The Downpour", "Weapons > Apprentice", "Cracked Shattered Sentinel Ratios Drippy Goblin", 261),
			new ("The Goblinator", "Pets > Exclusives", "Radiant Fortified Core Yeets Fortified Corruptor", 409),
			new ("The Perforator", "Weapons > Streamer", "Swift Nerfed Totem Boosts Beloved Cultist", 140),
			new ("The Prince's Glove", "Weapons > Squire", "Grim Juicy Protector Wins Corrupted Marauder", 72),
			new ("The Queen of Fire", "Pets > Exclusives", "Locked Swift Workshop Freezes Hardened Demon", 95),
			new ("The Rainmaker", "Weapons > Apprentice", "Endless Fire Sentinel Explodes Heroic Ogre", 305),
			new ("The Sins of the Jungle", "Weapons > Monk", "Tactical Fire Forge Defends Sweaty Minion", 210),
			new ("Thermopylae's Wrath", "Weapons > Exclusive", "Tilted Swift Champion Fortifies Chaotic Pack", 305),
			new ("Thorn of Nature", "Weapons > Monk", "Cracked Swift Relic Breaches Hardened Abomination", 76),
			new ("Thread of Destiny", "Accessories > Bracers", "Grim Radiant Barricade Throws Tilted Marauder", 77),
			new ("Thread of Life", "Accessories > Exclusives", "Endless Ancient Apprentice Freezes Brutal Ravager", 230),
			new ("Tinkerer's Demise", "Weapons > Squire", "Goated Shiny Forge Rushes Radiant Abomination", 174),
			new ("To Froya", "Weapons > Huntress", "Goated Fortified Armory Throws Tactical Ogre", 110),
			new ("Totally Real Chill Mammal", "Pets > Streamer", "Cracked Mid Crystal Defends Fragile Orc", 350),
			new ("Toy Sword", "Weapons > Squire", "Cracked Drippy Beacon Withstands Fortified Horde", 61),
			new ("Traffic Cone", "Accessories > Mid End Hats", "Endless Heroic Squire Shatters Cooked Assassin", 227),
			new ("Trick or Treater", "Pets > Collectibles", "Buffed Shiny Shiro Channels Nerfed Assassin", 98),
			new ("Ultimate Crystalline Defender", "Accessories > Shields", "Nerfed Ancient Shiro Spams Ancient Spider", 92),
			new ("Ultimate Crystalline Defender", "Accessories > Shields", "Corrupted Tactical Trap Breaches Mythic Spider", 92),
			new ("Ultimate Crystalline Defender", "Accessories > Shields", "Sweaty Brutal Lightning Spams Ancient Dragon", 92), // tigi
			new ("Ultimate Dungeon Defender", "Accessories > Shields", "Endless Shiny Workshop Fortifies Sweaty Wyvern", 404),
			new ("Umbriel", "Pets > Builder", "Chaotic Cracked Apprentice Camps Chaotic Wyvern", 94),
			new ("Unstoppable Jewel Mask", "Accessories > Mid End Masks", "Fire Grim Relic Builds Shiny Abomination", 70),
			new ("Valentine's Patch Celebration", "Accessories > High End Hats", "Brutal Beloved Shiro Fortifies Corrupted Wyvern", 624),
			new ("Valentine's Patch Celebration", "Accessories > High End Hats", "Fire Drippy Lightning Snowballs Mid Necromancer", 624),
			new ("Valentine's Patch Celebration", "Accessories > High End Hats", "Locked Enchanted Trap Smashes Mid Spider", 624),
			new ("Vamp's Delight", "Weapons > Monk", "Radiant Tilted Apprentice Shocks Buffed Abomination", 55),
			new ("Vanadis", "Weapons > Exclusive", "Swift Chaotic Obelisk Camps Brutal Wretch", 211),
			new ("Victoria", "Pets > Exclusives", "Beloved Tactical Trap Summons Enchanted Abomination", 1030),
			new ("Victoria", "Pets > Exclusives", "Grim Buffed Aura Freezes Shattered Horde", 1030),
			new ("Victoria", "Pets > Exclusives", "Swift Mythic Totem Repairs Buffed Assassin", 1030),
			new ("Vile Lord's Clutch", "Accessories > Bracers", "Fortified Endless Builder Carries Radiant Spider", 52),
			new ("Vortex Hammer", "Weapons > Squire", "Enchanted Brutal Tower Smashes Enchanted Demon", 62),
			new ("Vortex Shield", "Accessories > Shields", "Chaotic Mythic Fireball Snowballs Mythic Wyvern", 101),
			new ("War Bonnet", "Accessories > Mid End Hats", "Juicy Fortified Obelisk Snowballs Drippy Kobold", 70),
			new ("Waterfall", "Weapons > Apprentice", "Grim Cooked Huntress Camps Tilted Pillager", 81),
			new ("Web of Love", "Weapons > Huntress", "Shiny Buffed Vanguard Wipes Locked Brood", 55),
			new ("White Mage", "Pets > DPS", "Tactical Heroic Armory Snowballs Locked Destroyer", 279),
			new ("Woodland Prison", "Weapons > Squire", "Juicy Brutal Vanguard Launches Fire Cultist", 465),
			new ("Xenon's Shell Pole", "Weapons > Monk", "Tilted Fortified Barricade Breaches Nerfed Kobold", 47),
			new ("Yeti", "Pets > DPS", "Heroic Mythic Sigil Summons Hardened Overlord", 193),
			new ("Yggdrashield", "Accessories > Exclusives", "Shiny Radiant Defender Freezes Grim Pack", 469),
			new ("YGK's Extended Meat Carver", "Weapons > Squire", "Nerfed Cooked Relic Burns Hardened Ogre", 42),
			new ("Zappy Rainbows", "Weapons > Exclusive", "Cracked Ancient Monk Breaches Corrupted Wyvern", 535),
			new ("Zygomatic Sword", "Weapons > Exclusive", "Shiny Heroic Barricade Ratios Wild Wretch", 489),

		};
	}
}
