using System.ComponentModel.DataAnnotations.Schema;

namespace DDUP
{
	public static class EventPriceGuide
	{
		public static readonly Dictionary<string, int> Prices = new()
		{
			{ "Admiral Djinn", 37 },
			{ "Ahoy", 53 },
			{ "Aimer", 48 },
			{ "Air Plane", 109 },
			{ "Aladdins Wish", 42 },
			{ "Alpha", 601 },
			{ "aMAZEing Vision", 59 },
			{ "Amor 14k", 78 },
			{ "Amor 21k", 85 },
			{ "Amplifiers", 159 },
			{ "Ancient Plume", 91 },
			{ "Aphiry", 80 },
			{ "Armguard of Deforestation", 76 },
			{ "Armguard of Earth", 76 },
			{ "Armguard of Fire", 76 },
			{ "Armguard of Hate", 78 },
			{ "Armguard of Lightning", 82 },
			{ "Armguard of Love", 81 },
			{ "Armguard of Poison", 76 },
			{ "Armguard of Radiation", 78 },
			{ "Armguard of Smog", 79 },
			{ "Armguard of Toxic Waste", 75 },
			{ "Azure Peak", 66 },
			{ "Ball Blaster", 85 },
			{ "Battlecruiser Debris Mask", 52 },
			{ "Bean's Leftovers", 42 },
			{ "Black Mage", 500 },
			{ "bLACK mAGICK", 91 },
			{ "Black Satin Peak", 57 },
			{ "Black Shades", 932 },
			{ "Blahaj", 287 },
			{ "Blessed Brownie", 764 },
			{ "Bling! Bling! Bracers", 60 },
			{ "Blu", 51 },
			{ "Blueberry", 182 },
			{ "Bones", 248 },
			{ "Boneyard Blade", 47 },
			{ "Broken Heart", 2842 },
			{ "Butterscotch", 3175 },
			{ "Captain Djinn's Hat", 48 },
			{ "Captain Isom", 136 },
			{ "Carapace of the Queen", 59 },
			{ "Care Bear", 76 },
			{ "Eternal Gift", 346 },
			{ "Celebration", 499 },
			{ "Cheshire", 2750 },
			{ "Chicken Lover 3000", 43 },
			{ "Church", 188 },
			{ "Cinnabar", 76 },
			{ "Cinnamon", 183 },
			{ "Cloud Bracers", 326 },
			{ "Cobra's Whisper", 108 },
			{ "Copper Egg", 175 },
			{ "Crimson", 64 },
			{ "Cursed Brownie", 88 },
			{ "Darkling", 108 },
			{ "Death By Soda", 125 },
			{ "Death Wish", 45 },
			{ "Definitely A Berry", 56 },
			{ "Delver's Bracers", 593 },
			{ "Delver's Brooch", 743 },
			{ "Delver's Eyewear", 724 },
			{ "Dragon of the North", 51 },
			{ "Dunce Cap", 69 },
			{ "Dwarven Miners Mask", 43 },
			{ "Egg (Blue)", 113 },
			{ "Egg (Green)", 121 },
			{ "Egg (Red)", 121 },
			{ "Egg (Yellow)", 153 },
			{ "Elf Party Hat", 527 },
			{ "Eternity", 93 },
			{ "Excarlibug", 47 },
			{ "Expanders", 64 },
			{ "Face of RNG", 56 },
			{ "Fairy Floss on Rocks", 74 },
			{ "Falcor", 75 },
			{ "Fallen Bark", 52 },
			{ "Fearsome Trainer Mask", 44 },
			{ "Feathers of the Sky", 66 },
			{ "Final Patch", 484 },
			{ "Fire Balloon", 150 },
			{ "Firestorm", 57 },
			{ "First Contact", 64 },
			{ "Furious George", 40 },
			{ "Gaia's Last Gift", 117 },
			{ "Gamma", 411 },
			{ "Genie King's Prized Jewel", 55 },
			{ "Ginger", 246 },
			{ "Glaciers Demise", 279 },
			{ "GMO Giraffe", 110 },
			{ "Golden Egg", 179 },
			{ "Golden Roost", 47 },
			{ "Golden Shroom", 84 },
			{ "Golden Wood Shield", 161 },
			{ "Goron Tunic", 62 },
			{ "Grapes", 219 },
			{ "Greater Magicite of Christmas", 2913 },
			{ "Greater Magicite of Love", 11875 },
			{ "Greater Magicite of Pumpkin", 378 },
			{ "Greater Magicite of the Water", 20165 },
			{ "Greater Magicite of the Wind", 374 },
			{ "Grinch's #1 Fan", 42 },
			{ "Groovy Mask", 56 },
			{ "Honor Sword", 295 },
			{ "Hot Air Balloon", 425 },
			{ "Howling Werewolf", 45 },
			{ "Inkzooka", 56 },
			{ "Iratxo", 78 },
			{ "Jack in The Box", 200 },
			{ "Jason Vorhees Mask", 43 },
			{ "Juicy Fruit", 226 },
			{ "Kraken's Good Eye", 49 },
			{ "Krampus Hat", 225 },
			{ "Lava Cuffs", 54 },
			{ "Lava Dancer Mask", 50 },
			{ "Lettuce", 65 },
			{ "Liebe", 283 },
			{ "Lieutenant Sparkles", 92 },
			{ "LimePie", 204 },
			{ "Limetori", 2125 },
			{ "Lumen", 59 },
			{ "Lunar Demon", 54 },
			{ "Lunar Magic", 43 },
			{ "Mad Joe", 48 },
			{ "Maelstrom", 51 },
			{ "Magnificators", 104 },
			{ "Magora's Mask", 48 },
			{ "Malory", 650 },
			{ "Mana Master", 45 },
			{ "Marid", 41 },
			{ "Mars", 53 },
			{ "Mask of Legends", 88 },
			{ "Mask of the Pumpkin King", 59 },
			{ "Memoriam", 89 },
			{ "Mezcal", 168 },
			{ "Mike", 8355 },
			{ "Minish Hat", 45 },
			{ "Misri", 69 },
			{ "Molon Labe", 138 },
			{ "Moraggo's Secret Treasure", 69 },
			{ "Mr Bed", 1285 },
			{ "Mr Crackers", 407 },
			{ "Mr Skelly", 55 },
			{ "Munchkin", 127 },
			{ "Mustard", 134 },
			{ "Mutated Hand", 45 },
			{ "Natori", 286 },
			{ "Neptune", 133 },
			{ "New Patch Celebration", 530 },
			{ "Obunga's Other Half", 71 },
			{ "Ocean", 61 },
			{ "Odin's Mask", 44 },
			{ "Olaf", 413 },
			{ "Old One's Stache", 46 },
			{ "Overload", 112 },
			{ "Overlord", 125 },
			{ "Paper Straw", 150 },
			{ "Party Horn", 72 },			
			{ "PB&J", 857 },
			{ "Pegasus Boots", 42 },
			{ "Personal Resort", 267 },
			{ "Phrosty", 9 },
			{ "Ploutonion", 132 },
			{ "Pole of the North Star", 1042 },
			{ "Pole of the South Star", 107 },
			{ "Poseidon's Shorebreaker", 147 },
			{ "Power Gauntlets", 50 },
			{ "Proto VPC", 4000 },
			{ "Pumpkin Head Celebration", 542 },
			{ "Pumpkin Peak", 55 },
			{ "Queen Georgia", 60 },
			{ "Raspberry Staff", 283 },
			{ "Red", 54 },
			{ "Retinazer", 308 },
			{ "Rock's Feather", 50 },
			{ "Rockshatter", 111 },
			{ "Rosemary", 243 },
			{ "Sahara", 62 },
			{ "Salem", 69 },
			{ "Santa's Spare Hat", 61 },
			{ "Sapphire", 52 },
			{ "Serpent of the North", 71 },
			{ "Shield of Mirrors", 52 },
			{ "Silver Egg", 192 },
			{ "Skittles (Blue)", 50 },
			{ "Skittles (Green)", 50 },
			{ "Skittles (Orange)", 50 },
			{ "Skittles (Pink)", 65 },
			{ "Skittles (Purple)", 50 },
			{ "Skittles (Red)", 50 },
			{ "Skittles (Yellow)", 60 },
			{ "Snowballer 3000", 37 },
			{ "Something Blue", 56 },
			{ "Something Coral", 50 },
			{ "Something Crimson", 50 },
			{ "Something Fuschia", 50 },
			{ "Something Green", 50 },
			{ "Something Lemon", 50 },
			{ "Something Lime", 50 },
			{ "Something Navy", 73 },
			{ "Something Orange", 60 },
			{ "Something Pink", 1059 },
			{ "Something Purple", 45 },
			{ "Something Red", 57 },
			{ "Something Violet", 50 },
			{ "Something Yellow", 50 },
			{ "Spartan Shield", 133 },
			{ "Spartan Spear", 113 },
			{ "Spazmatism", 256 },
			{ "Spearmint", 46 },
			{ "Speed Freak Feather", 40 },
			{ "Speedster", 49 },
			{ "Speedy", 45 },
			{ "Speedy Cloud Bracers", 909 },
			{ "Splash Ops", 72 },
			{ "Spoony lvl 100", 1200 },
			{ "Staff of the Pumpkin King", 50 },
			{ "Stieglitz", 134 },
			{ "Strawberry", 213 },
			{ "Strawberry Rock", 150 },
			{ "Sun Staff", 400 },
			{ "Sword of Valor (Blue)", 46 },
			{ "Sword of Valor (Green)", 46 },
			{ "Sword of Valor (Red)", 46 },
			{ "Tabula Rasa", 300 },
			{ "Talay's Doom", 64 },
			{ "Terra's Magicite Brooch", 40 },
			{ "Tess", 463 },
			{ "The Cavalry", 63 },
			{ "The Devil's Poolskimmer", 52 },
			{ "The Downpour", 261 },
			{ "The Goblinator", 393 },
			{ "The Prince's Glove", 79 },
			{ "The Queen of Fire", 75 },
			{ "The Rainmaker", 270 },
			{ "Thermopylae's Wrath", 80 },
			{ "Thorn of Nature", 69 },
			{ "Thread of Destiny", 80 },
			{ "Thread of Life", 95 },
			{ "Tinkerer's Demise", 148 },
			{ "To Froya", 125 },
			{ "Toy Sword", 53 },
			{ "Trick or Treater", 100 },
			{ "Ultimate Crystalline Defender", 93 },
			{ "Ultimate Dungeon Defender", 560 },
			{ "Umbriel", 90 },
			{ "Unstoppable Jewel Mask", 65 },
			{ "Valentine's Patch Celebration", 528 },
			{ "Vamp's Delight", 50 },
			{ "Vanadis", 129 },
			{ "Victoria", 908 },
			{ "Vile Lord's Clutch", 47 },
			{ "Vortex Hammer", 54 },
			{ "Vortex Shield", 98 },
			{ "War Bonnet", 71 },
			{ "Waterfall", 75 },
			{ "Web of Love", 49 },
			{ "White Mage", 243 },
			{ "Woodland Prison", 119 },
			{ "Xenon's Shell Pole", 45 },
			{ "Yeti", 250 },
			{ "Yggdrashield", 307 },
			{ "YGK's Extended Meat Carver", 41 },
			{ "Zappy Rainbows", 319 },
			{ "Zygomatic Sword", 254 },			
		};
	}

}
