using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DDUP
{	
	public struct EventItemInfo
	{
		public string ItemName;
		public string HashPhrase;
		public string Category;
		public uint NumericHash;

		public string NewHashPhrase = "";
		public uint NewNumericHash;
		public int Price;

		public EventItemInfo(string itemName, string category, string hashPhrase, int price)
		{
			ItemName = itemName;
			Category = category;
			HashPhrase = hashPhrase;
			Price = price;
			NumericHash = 0;
			ItemHash.TryPhraseToInt30(hashPhrase, out NumericHash);
			EventPriceGuide.HashToEventInfo[NumericHash] = this;			
		}			
	}

	public static class EventPriceGuide
	{
		public static Dictionary<uint, EventItemInfo> HashToEventInfo = [];		
		static readonly EventItemInfo[] EventInfo = 
		{
			new ("Admiral Djinn", "Pets > Collectibles", "Tactical Shiny Core Shatters Drippy Demon", 37),
			new ("Ahoy", "Pets > DPS", "Ancient Hardened Protector Pops Tactical Minion", 53),
			new ("Aimer", "Pets > DPS", "Goated Juicy Sigil Locks Goated Berserker", 48),
			new ("Air Plane", "Pets > DPS", "Shattered Shiny Fireball Snowballs Chaotic Necromancer", 109),
			new ("Aladdins Wish", "Weapons > Huntress", "Hardened Fragile Stronghold Launches Mythic Spider", 42),
			new ("Alpha", "Pets > Exclusives", "Luminous Beloved Apprentice Fortifies Brutal Goblin", 601),
			new ("aMAZEing Vision", "Accessories > Masks", "Shattered Locked Barricade Farms Heroic Spider", 59),
			new ("Amor 14k", "Pets > Collectibles", "Juicy Radiant Sigil Locks Fire Invader", 78),
			new ("Amor 21k", "Pets > Collectibles", "Cracked Tilted Harpoon Fortifies Fragile Corruptor", 85),
			new ("Amplifiers", "Accessories > Mid End Bracers", "Cooked Fire Sentinel Deletes Tactical Orc", 159),
			new ("Ancient Plume", "Accessories > Mid End Hats", "Locked Endless Trap Deletes Luminous Wyvern", 91),
			new ("Aphiry", "Pets > Streamer", "Radiant Locked Relic Repels Wild Pack", 80),
			new ("Armguard of Deforestation", "Accessories > Bracers", "Sweaty Shattered Beacon Summons Hardened Swarm", 76),
			new ("Armguard of Earth", "Accessories > Bracers", "Locked Goated Workshop Spams Chaotic Spider", 76),
			new ("Armguard of Fire", "Accessories > Bracers", "Tactical Beloved Spike Rushes Mythic Wretch", 76),
			new ("Armguard of Hate", "Accessories > Bracers", "Buffed Juicy Banner Locks Ancient Dragon", 78),
			new ("Armguard of Lightning", "Accessories > Bracers", "Locked Swift Sigil Withstands Shiny Kobold", 82),
			new ("Armguard of Love", "Accessories > Bracers", "Radiant Cracked Champion Shatters Luminous Corruptor", 81),
			new ("Armguard of Poison", "Accessories > Bracers", "Juicy Brutal Banner Withstands Swift Necromancer", 76),
			new ("Armguard of Radiation", "Accessories > Bracers", "Tilted Tilted Core Clutches Luminous Cultist", 78),
			new ("Armguard of Smog", "Accessories > Bracers", "Grim Brutal Relic Carries Drippy Brute", 79),
			new ("Armguard of Toxic Waste", "Accessories > Bracers", "Mid Swift Builder Shatters Nerfed Fiend", 75),
			new ("Azure Peak", "Accessories > Mid End Hats", "Shiny Beloved Huntress Deletes Brutal Assassin", 66),
			new ("Ball Blaster", "Weapons > Monk", "Locked Tilted Huntress Throws Enchanted Pack", 85),
			new ("Battlecruiser Debris Mask", "Accessories > Masks", "Ancient Fire Workshop Repairs Fragile Shaman", 52),
			new ("Bean's Leftovers", "Accessories > Masks", "Wild Brutal Squire Builds Enchanted Wyvern", 42),
			new ("Black Mage", "Pets > Exclusives", "Heroic Hardened Armory Launches Tilted Goblin", 500),
			new ("bLACK mAGICK", "Pets > DPS", "Corrupted Nerfed Beacon Pops Tactical Berserker", 91),
			new ("Black Satin Peak", "Accessories > Mid End Hats", "Brutal Radiant Obelisk Shocks Cracked Brute", 57),
			new ("Black Shades", "Accessories > High End Masks", "Heroic Chaotic Trap Shocks Fire Wretch", 932),
			new ("Blahaj", "Pets > DPS", "Mythic Enchanted Obelisk Rushes Beloved Pack", 287),
			new ("Blessed Brownie", "Pets > Exclusives", "Grim Brutal Sigil Deletes Heroic Fiend", 764), //2021
			new ("Blessed Brownie", "Pets > Exclusives", "Juicy Enchanted Totem Locks Sweaty Wretch", 764), //2023
			new ("Blessed Brownie", "Pets > Exclusives", "Fortified Luminous Lightning Camps Locked Invader", 764), //2024
			new ("Bling! Bling! Bracers", "Accessories > Bracers", "Fortified Mythic Warden Deletes Corrupted Shaman", 60),
			new ("Blu", "Pets > Collectibles", "Beloved Ancient Fireball Repels Juicy Overlord", 51),
			new ("Blueberry", "Pets > Guardians", "Enchanted Buffed Stronghold Channels Heroic Wyvern", 182),
			new ("Bones", "Pets > Exclusives", "Chaotic Hardened Squire Carries Mid Goblin", 248),
			new ("Boneyard Blade", "Weapons > Squire", "Grim Nerfed Monk Channels Enchanted Abomination", 47),
			new ("Broken Heart", "Pets > Exclusives", "Endless Drippy Relic Builds Buffed Pillager", 2842),
			new ("Butterscotch", "Pets > Exclusives", "Mid Fortified Totem Breaches Fire Ogre", 3175),
			new ("Captain Djinn's Hat", "Accessories > Hats", "Corrupted Juicy Totem Locks Endless Swarm", 48),
			new ("Captain Isom", "Pets > Collectibles", "Cooked Wild Totem Deletes Juicy Warlock", 136),
			new ("Carapace of the Queen", "Accessories > Shields", "Locked Nerfed Crystal Wins Mythic Brood", 59),
			new ("Care Bear 300/1", "unknown", "Corrupted Cooked Core Boosts Shiny Invader", 10000), //? auction price?
			new ("Care Bear", "Pets > Collectibles", "Shiny Mid Beacon Defends Cracked Abomination", 76),
			new ("Celebracers", "Accessories > High End Bracers", "Fire Goated Aura Summons Goated Kobold", 346),
			new ("Celebration", "Accessories > High End Hats", "Brutal Cracked Totem Wins Shiny Kobold", 499),
			new ("Cheshire", "Pets > Exclusives", "Tilted Goated Guardian Explodes Drippy Assassin", 2750),
			new ("Chicken Lover 3000", "Weapons > Monk", "Fire Enchanted Builder Freezes Hardened Berserker", 43),
			new ("Church", "Pets > DPS", "Luminous Wild Sigil Clutches Tactical Warlock", 188),
			new ("Cinnabar", "Pets > Collectibles", "Goated Drippy Guardian Fortifies Corrupted Invader", 76),
			new ("Cinnamon", "Pets > Guardians", "Luminous Brutal Obelisk Boosts Swift Raider", 183),
			new ("Cloud Bracers", "Accessories > High End Bracers", "Cooked Endless Monk Wipes Fire Swarm", 326),
			new ("Cobra's Whisper", "Weapons > Apprentice", "Ancient Nerfed Guardian Fortifies Locked Minion", 108),
			new ("Copper Egg", "Pets > Builder", "Mid Chaotic Warden Summons Nerfed Invader", 175),
			new ("Crimson", "Weapons > Squire", "Wild Grim Huntress Clutches Buffed Shaman", 64),
			new ("Cursed Brownie", "Pets > Collectibles", "Tilted Corrupted Beacon Spams Heroic Abomination", 88),
			new ("Darkling", "Pets > Streamer", "Tactical Chaotic Apprentice Throws Cracked Fiend", 108),
			new ("Death By Soda", "Weapons > Huntress", "Cooked Enchanted Forge Repels Shiny Marauder", 125),
			new ("Death Wish", "Weapons > Huntress", "Swift Chaotic Defender Smashes Buffed Brood", 45),
			new ("Definitely A Berry", "Weapons > Apprentice", "Fragile Ancient Squire Channels Sweaty Pillager", 56),
			new ("Delver's Bracers", "Accessories > High End Bracers", "Mythic Beloved Banner Freezes Fortified Raider", 593),
			new ("Delver's Brooch", "Accessories > High End Hats", "Radiant Beloved Spike Shatters Radiant Corruptor", 743),
			new ("Delver's Eyewear", "Accessories > High End Masks", "Mid Fortified Lightning Deletes Hardened Orc", 724),
			new ("Dragon of the North", "Accessories > Bracers", "Shattered Shattered Barricade Shatters Enchanted Swarm", 51),
			new ("Dunce Cap", "Accessories > Mid End Hats", "Fragile Cracked Trap Shocks Mid Fiend", 69),
			new ("Dunce Cap", "Accessories > Mid End Hats", "Heroic Hardened Trap Shocks Hardened Fiend", 69),
			new ("Dwarven Miners Mask", "Accessories > Masks", "Enchanted Juicy Aura Wipes Goated Brood", 43),
			new ("Egg (Blue)", "Pets > Builder", "Enchanted Nerfed Vanguard Throws Fortified Corruptor", 113),
			new ("Egg (Green)", "Pets > Builder", "Brutal Nerfed Apprentice Snowballs Sweaty Necromancer", 121),
			new ("Egg (Red)", "Pets > Builder", "Enchanted Hardened Warden Launches Grim Assassin", 121),
			new ("Egg (Yellow)", "Pets > Builder", "Enchanted Shiny Crystal Explodes Beloved Wyvern", 153),
			new ("Elf Party Hat", "Accessories > High End Hats", "Tactical Corrupted Huntress Wipes Tilted Brute", 527),
			new ("Eternity", "Accessories > Mid End Bracers", "Endless Enchanted Lightning Fortifies Enchanted Berserker", 93),
			new ("Excarlibug", "Weapons > Apprentice", "Shiny Endless Defender Repairs Shiny Horde", 47),
			new ("Expanders", "Accessories > Mid End Hats", "Drippy Enchanted Forge Farms Buffed Wretch", 64),
			new ("Face of RNG", "Accessories > Masks", "Brutal Hardened Builder Repairs Enchanted Necromancer", 56),
			new ("Fairy Floss on Rocks", "Accessories > Mid End Bracers", "Nerfed Nerfed Fireball Wins Shattered Kobold", 74),
			new ("Falcor", "Pets > Collectibles", "Mid Goated Tower Throws Shiny Overlord", 75),
			new ("Fallen Bark", "Accessories > Mid End Bracers", "Endless Drippy Monk Wins Shiny Assassin", 52),
			new ("Fearsome Trainer Mask", "Accessories > Masks", "Nerfed Drippy Guardian Builds Chaotic Invader", 44),
			new ("Feathers of the Sky", "Accessories > Mid End Hats", "Hardened Tilted Fireball Wipes Tactical Shaman", 66),
			new ("Final Patch", "Accessories > High End Masks", "Chaotic Fragile Crystal Throws Heroic Swarm", 484),
			new ("Fire Balloon", "Pets > DPS", "Mythic Shattered Obelisk Burns Fragile Assassin", 150),
			new ("Firestorm", "Weapons > Huntress", "Mid Beloved Sigil Breaches Grim Swarm", 57),
			new ("First Contact", "Weapons > Monk", "Sweaty Brutal Relic Burns Drippy Warlock", 64),
			new ("Furious George", "Pets > Collectibles", "Tilted Fragile Warden Carries Chaotic Necromancer", 40),
			new ("Gaia's Last Gift", "Weapons > Huntress", "Fortified Shattered Spike Farms Ancient Destroyer", 117),
			new ("Gamma", "Pets > Exclusives", "Luminous Shattered Totem Pops Mythic Invader", 411),
			new ("Genie King's Prized Jewel", "Accessories > Hats", "Tactical Locked Sigil Defends Mid Invader", 55),
			new ("Ginger", "Pets > Guardians", "Cooked Enchanted Apprentice Boosts Tactical Ravager", 246),
			new ("Glaciers Demise", "Weapons > Squire", "Hardened Fire Trap Withstands Cooked Kobold", 279),
			new ("GMO Giraffe", "Pets > Builder", "Fire Heroic Relic Repairs Goated Shaman", 110),
			new ("Golden Egg", "Pets > Builder", "Mid Chaotic Aura Ratios Drippy Goblin", 179),
			new ("Golden Roost", "Weapons > Huntress", "Shiny Drippy Protector Pops Ancient Horde", 47),
			new ("Golden Shroom", "Pets > Collectibles", "Cracked Tilted Tower Smashes Grim Abomination", 84),
			new ("Golden Wood Shield", "Accessories > Shields", "Enchanted Fortified Relic Burns Tilted Orc", 161),
			new ("Goron Tunic", "Accessories > Armor Pieces", "Drippy Beloved Warden Farms Mythic Ravager", 62),
			new ("Grapes", "Pets > Guardians", "Nerfed Radiant Vanguard Farms Mythic Pack", 219),
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Brutal Fragile Vanguard Breaches Enchanted Ogre", 2913), // 2021
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Drippy Cracked Workshop Ratios Cracked Overlord", 2913), // 2018
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Fragile Grim Champion Yeets Corrupted Corruptor", 2913), // 2019
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Fragile Grim Champion Yeets Corrupted Corruptor", 2913), // 2023
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Hardened Buffed Lightning Pops Enchanted Goblin", 2913), // 2022
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Luminous Tilted Totem Throws Luminous Destroyer", 2913), // 2020
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Shiny Wild Apprentice Rushes Sweaty Goblin", 2913), // 2024
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Sweaty Mythic Armory Freezes Hardened Raider", 2913), // 2025?
			new ("Greater Magicite of Christmas", "Pets > Exclusives", "Swift Buffed Barricade Shatters Tilted Orc", 2913), // 2017
			new ("Greater Magicite of Love", "Pets > Exclusives", "Brutal Heroic Stronghold Boosts Luminous Invader", 11875), // 2024
			new ("Greater Magicite of Love", "Pets > Exclusives", "Endless Locked Builder Wipes Ancient Swarm", 11875), // 2022
			new ("Greater Magicite of Love", "Pets > Exclusives", "Hardened Swift Fireball Boosts Fragile Berserker", 11875), // 2023
			new ("Greater Magicite of Love", "Pets > Exclusives", "Juicy Corrupted Obelisk Locks Nerfed Pillager", 11875), // 2025
			new ("Greater Magicite of Love", "Pets > Exclusives", "Shiny Beloved Crystal Farms Drippy Kobold", 11875), // 2026
			new ("Greater Magicite of Pumpkin", "Pets > Builder", "Hardened Nerfed Fireball Throws Shiny Shaman", 378), // 2022
			new ("Greater Magicite of the Water", "Pets > Exclusives", "Chaotic Shiny Monk Spams Hardened Minion", 20165), // 2025
			new ("Greater Magicite of the Water", "Pets > Exclusives", "Tactical Shiny Champion Summons Sweaty Wretch", 20165), // 2022
			new ("Greater Magicite of the Water", "Pets > Exclusives", "Wild Cracked Obelisk Locks Tilted Overlord", 20165), // 2024
			new ("Greater Magicite of the Wind", "Pets > Builder", "Tilted Mid Stronghold Repels Chaotic Berserker", 374),
			new ("Grinch's #1 Fan", "Pets > Collectibles", "Fortified Radiant Obelisk Shatters Endless Pillager", 42),
			new ("Groovy Mask", "Accessories > Masks", "Brutal Brutal Crystal Boosts Cracked Horde", 56),
			new ("Honor Sword", "Weapons > Exclusive", "Chaotic Buffed Protector Launches Swift Abomination", 295),
			new ("Hot Air Balloon", "Pets > Exclusives", "Nerfed Mid Guardian Spams Drippy Ogre", 425),
			new ("Howling Werewolf", "Weapons > Huntress", "Hardened Buffed Squire Freezes Mythic Wyvern", 45),
			new ("Inkzooka", "Weapons > Huntress", "Chaotic Tactical Fireball Deletes Sweaty Berserker", 56),
			new ("Iratxo", "Pets > Collectibles", "Corrupted Nerfed Fireball Throws Hardened Cultist", 78),
			new ("Jack in The Box", "Pets > DPS", "Swift Brutal Harpoon Ratios Hardened Horde", 200),
			new ("Jason Vorhees Mask", "Accessories > Masks", "Shattered Juicy Obelisk Withstands Juicy Wyvern", 43),
			new ("Juicy Fruit", "Pets > Streamer", "Fragile Fire Workshop Withstands Drippy Cultist", 226),
			new ("Kraken's Good Eye", "Accessories > Masks", "Swift Drippy Relic Yeets Shattered Minion", 49),
			new ("Krampus Hat", "Accessories > Exclusives", "Cracked Luminous Forge Wipes Fortified Dragon", 225),
			new ("Lava Cuffs", "Accessories > Bracers", "Fragile Ancient Champion Throws Fragile Shaman", 54),
			new ("Lava Dancer Mask", "Accessories > Masks", "Cooked Tilted Warden Launches Cracked Horde", 50),
			new ("Lettuce", "Pets > DPS", "Enchanted Luminous Lightning Wipes Wild Minion", 65),
			new ("Liebe", "Pets > Exclusives", "Hardened Buffed Builder Locks Fortified Ogre", 283),
			new ("Lieutenant Sparkles", "Pets > Collectibles", "Wild Fragile Crystal Pops Mid Berserker", 92),
			new ("LimePie", "Pets > Guardians", "Shiny Cooked Armory Boosts Shattered Invader", 204),
			new ("Limetori", "Pets > Exclusives", "Fortified Swift Protector Fortifies Juicy Swarm", 2125),
			new ("Lumen", "Weapons > Huntress", "Fortified Luminous Banner Ratios Endless Brute", 59),
			new ("Lunar Demon", "Weapons > Apprentice", "Nerfed Tactical Warden Rushes Hardened Ravager", 54),
			new ("Lunar Magic", "Weapons > Apprentice", "Enchanted Luminous Monk Channels Cooked Ravager", 43),
			new ("Mad Joe", "Pets > Collectibles", "Cracked Endless Relic Ratios Brutal Berserker", 48),
			new ("Maelstrom", "Weapons > Apprentice", "Locked Chaotic Huntress Repairs Fire Berserker", 51),
			new ("Magnificators", "Accessories > Mid End Masks", "Mythic Endless Armory Clutches Beloved Corruptor", 104),
			new ("Magora's Mask", "Accessories > Masks", "Mythic Mythic Defender Camps Mid Necromancer", 48),
			new ("Malory", "Pets > Exclusives", "Buffed Corrupted Tower Freezes Heroic Brood", 650),
			new ("Mana Master", "Pets > Collectibles", "Locked Brutal Sentinel Withstands Fragile Orc", 45),
			new ("Marid", "Pets > Builder", "Wild Buffed Huntress Pops Nerfed Necromancer", 41),
			new ("Mars", "Pets > Builder", "Fortified Tactical Guardian Burns Tactical Shaman", 53),
			new ("Mask of Legends", "Accessories > Mid End Masks", "Corrupted Nerfed Stronghold Pops Goated Beast", 88),
			new ("Mask of the Pumpkin King", "Accessories > Mid End Masks", "Chaotic Endless Vanguard Repels Sweaty Marauder", 59),
			new ("Memoriam", "Accessories > Mid End Bracers", "Heroic Endless Squire Snowballs Endless Destroyer", 89),
			new ("Mezcal", "Pets > Streamer", "Tilted Grim Beacon Throws Wild Kobold", 168),
			new ("Mike", "Pets > Exclusives", "Fragile Cracked Apprentice Shatters Brutal Minion", 8355),
			new ("Mining Etheria in search of vast wealth", "unknown", "Enchanted Juicy Aura Wipes Goated Brood", 10000), //? no auction price
			new ("Minish Hat", "Accessories > Armor Pieces", "Endless Mid Stronghold Fortifies Goated Beast", 45),
			new ("Misri", "Accessories > Mid End Hats", "Goated Fire Obelisk Fortifies Locked Brute", 69),
			new ("Molon Labe", "Accessories > Exclusives", "Sweaty Sweaty Aura Breaches Luminous Raider", 138),
			new ("Moraggo's Secret Treasure", "Weapons > Monk", "Goated Cooked Totem Shatters Buffed Spider", 69),
			new ("Mr Bed", "Pets > Exclusives", "Cooked Shiny Totem Explodes Drippy Raider", 1285),
			new ("Mr Crackers", "Pets > DPS", "Radiant Tilted Warden Repairs Goated Swarm", 407),
			new ("Mr Skelly", "Pets > Builder", "Endless Mythic Beacon Defends Sweaty Swarm", 55),
			new ("Munchkin", "Pets > DPS", "Ancient Juicy Workshop Summons Corrupted Necromancer", 127),
			new ("Mustard", "Pets > Guardians", "Mythic Brutal Guardian Boosts Cracked Fiend", 134),
			new ("Mutated Hand", "Weapons > Squire", "Ancient Drippy Champion Freezes Beloved Overlord", 45),
			new ("Natori", "Pets > DPS", "Fire Radiant Sentinel Smashes Juicy Pillager", 286),
			new ("Neptune", "Pets > Builder", "Shiny Tilted Beacon Wins Fragile Ogre", 133),
			new ("New Patch Celebration", "Accessories > High End Hats", "Corrupted Radiant Sentinel Boosts Goated Ogre", 530),
			new ("Obunga's Other Half", "Pets > Streamer", "Mythic Radiant Harpoon Clutches Drippy Shaman", 71),
			new ("Ocean", "Accessories > Mid End Masks", "Brutal Nerfed Fireball Carries Sweaty Wyvern", 61),
			new ("Odin's Mask", "Accessories > Masks", "Mythic Mid Tower Carries Chaotic Goblin", 44),
			new ("Olaf", "Pets > Exclusives", "Cracked Radiant Aura Throws Radiant Brood", 413),
			new ("Old One's Stache", "Accessories > Masks", "Enchanted Enchanted Protector Breaches Shiny Horde", 46),
			new ("Overload", "Pets > Builder", "Grim Shattered Forge Defends Cracked Invader", 112),
			new ("Overlord", "Pets > Streamer", "Swift Shattered Squire Repels Ancient Assassin", 125),
			new ("Paper Straw", "Weapons > Exclusive", "Fire Radiant Crystal Burns Mythic Kobold", 150),
			new ("Party Horn", "Accessories > Mid End Masks", "Endless Endless Workshop Summons Buffed Spider", 72),
			new ("PB&J", "Pets > Exclusives", "Sweaty Juicy Harpoon Carries Sweaty Warlock", 857),
			new ("Pegasus Boots", "Accessories > Armor Pieces", "Grim Fortified Champion Shocks Fragile Kobold", 42),
			new ("Personal Resort", "Pets > Streamer", "Enchanted Shattered Stronghold Camps Cooked Brute", 267),
			new ("Phrosty", "Pets > Streamer", "Mythic Luminous Lightning Shatters Cracked Pack", 9),
			new ("Ploutonion", "Accessories > Shields", "Mid Radiant Lightning Locks Cracked Destroyer", 132),
			new ("Pole of the North Star", "Weapons > Exclusive", "Buffed Grim Crystal Burns Beloved Cultist", 1042),
			new ("Pole of the South Star", "Weapons > Apprentice", "Cooked Grim Huntress Fortifies Beloved Kobold", 107),
			new ("Poseidon's Shorebreaker", "Weapons > Monk", "Goated Endless Champion Ratios Goated Pack", 147),
			new ("Power Gauntlets", "Accessories > Armor Pieces", "Drippy Cooked Barricade Explodes Hardened Abomination", 50),
			new ("Proto VPC", "Accessories > Exclusives", "Ancient Locked Apprentice Pops Cooked Fiend", 4000),
			new ("Pumpkin Head Celebration", "Accessories > High End Hats", "Brutal Swift Trap Wipes Shattered Dragon", 542),
			new ("Pumpkin Peak", "Accessories > Mid End Hats", "Tactical Wild Champion Yeets Luminous Assassin", 55),
			new ("Queen Georgia", "Pets > DPS", "Chaotic Buffed Harpoon Snowballs Goated Ogre", 60),
			new ("Raspberry Staff", "Weapons > Exclusive", "Fragile Buffed Armory Fortifies Beloved Assassin", 283),
			new ("Red", "Pets > DPS", "Endless Nerfed Aura Shocks Mythic Goblin", 54),
			new ("Retinazer", "Pets > DPS", "Drippy Fragile Aura Throws Swift Overlord", 308),
			new ("Rock's Feather", "Accessories > Hats", "Mythic Swift Lightning Summons Ancient Cultist", 50),
			new ("Rockshatter", "Weapons > Huntress", "Fragile Fragile Sigil Shatters Chaotic Kobold", 111),
			new ("Rosemary", "Pets > Streamer", "Beloved Corrupted Vanguard Defends Mythic Beast", 243),
			new ("Sahara", "Weapons > Apprentice", "Chaotic Brutal Aura Farms Juicy Minion", 62),
			new ("Salem", "Pets > DPS", "Shattered Endless Sigil Burns Goated Ravager", 69),
			new ("Santa's Spare Hat", "Accessories > Mid End Hats", "Tilted Swift Builder Burns Hardened Assassin", 61),
			new ("Sapphire", "Weapons > Squire", "Tilted Juicy Warden Repairs Drippy Raider", 52),
			new ("Serpent of the North", "Pets > DPS", "Juicy Endless Harpoon Summons Goated Overlord", 71),
			new ("Shield of Mirrors", "Accessories > Shields", "Mythic Brutal Sentinel Yeets Drippy Destroyer", 52),
			new ("Silver Egg", "Pets > Builder", "Fragile Wild Squire Launches Ancient Pack", 192),
			new ("Skittles (Blue)", "Pets > DPS", "Endless Corrupted Builder Carries Corrupted Cultist", 50),
			new ("Skittles (Green)", "Pets > DPS", "Buffed Brutal Armory Fortifies Drippy Fiend", 50),
			new ("Skittles (Orange)", "Pets > DPS", "Swift Chaotic Spike Repairs Fragile Goblin", 50),
			new ("Skittles (Pink)", "Pets > DPS", "Swift Beloved Monk Spams Cooked Ravager", 65),
			new ("Skittles (Purple)", "Pets > DPS", "Ancient Sweaty Monk Wins Endless Invader", 50),
			new ("Skittles (Red)", "Pets > DPS", "Ancient Cracked Vanguard Freezes Cracked Demon", 50),
			new ("Skittles (Yellow)", "Pets > DPS", "Juicy Tactical Banner Smashes Chaotic Orc", 60),
			new ("Snowballer 3000", "Weapons > Huntress", "Fragile Sweaty Squire Freezes Shiny Corruptor", 37),
			new ("Something Blue", "Accessories > Hats", "Ancient Tactical Builder Deletes Cooked Overlord", 56),
			new ("Something Coral", "Accessories > Hats", "Cracked Ancient Armory Breaches Enchanted Abomination", 50),
			new ("Something Crimson", "Accessories > Hats", "Shattered Wild Spike Wipes Fortified Brute", 50),
			new ("Something Fuschia", "Accessories > Hats", "Fortified Radiant Lightning Shatters Tactical Horde", 50),
			new ("Something Green", "Accessories > Hats", "Ancient Grim Beacon Farms Ancient Minion", 50),
			new ("Something Lemon", "Accessories > Hats", "Fire Sweaty Apprentice Spams Brutal Necromancer", 50),
			new ("Something Lime", "Accessories > Hats", "Brutal Ancient Obelisk Withstands Buffed Fiend", 50),
			new ("Something Navy", "Accessories > Hats", "Brutal Tactical Relic Fortifies Hardened Ravager", 73),
			new ("Something Orange", "Accessories > Hats", "Nerfed Luminous Monk Channels Hardened Necromancer", 60),
			new ("Something Pink", "Accessories > Exclusives", "Grim Sweaty Fireball Channels Sweaty Shaman", 1059),
			new ("Something Purple", "Accessories > Hats", "Fire Wild Obelisk Burns Beloved Marauder", 45),
			new ("Something Red", "Accessories > Hats", "Nerfed Brutal Obelisk Farms Sweaty Ravager", 57),
			new ("Something Violet", "Accessories > Hats", "Mid Juicy Builder Launches Cooked Brute", 50),
			new ("Something Yellow", "Accessories > Hats", "Grim Radiant Relic Carries Brutal Beast", 50),
			new ("Spartan Shield", "Accessories > Shields", "Locked Tactical Stronghold Shocks Buffed Invader", 133),
			new ("Spartan Spear", "Weapons > Monk", "Tilted Hardened Monk Carries Tactical Cultist", 113),
			new ("Spazmatism", "Pets > DPS", "Sweaty Ancient Monk Smashes Mid Demon", 256),
			new ("Spearmint", "Weapons > Monk", "Fortified Nerfed Armory Carries Mid Fiend", 46),
			new ("Speed Freak Feather", "Accessories > Hats", "Wild Grim Lightning Camps Cooked Marauder", 40),
			new ("Speedster", "Pets > Collectibles", "Heroic Swift Fireball Freezes Hardened Invader", 49),
			new ("Speedy Cloud Bracers", "Accessories > Exclusives", "Swift Locked Champion Freezes Hardened Invader", 909),
			new ("Speedy", "Pets > DPS", "Tactical Fire Obelisk Repairs Cooked Wyvern", 45),
			new ("Splash Ops", "Weapons > Huntress", "Sweaty Goated Defender Camps Chaotic Horde", 72),
			new ("Spoony lvl 100", "Weapons > Exclusive", "Wild Buffed Apprentice Repels Mid Ravager", 1200),
			new ("Staff of the Pumpkin King", "Weapons > Apprentice", "Cooked Grim Sentinel Wipes Swift Swarm", 50),
			new ("Stieglitz", "Pets > Collectibles", "Grim Fortified Protector Ratios Tactical Dragon", 134),
			new ("Strawberry Rock", "Pets > Collectibles", "Corrupted Fortified Forge Rushes Tilted Pillager", 150),
			new ("Strawberry", "Pets > Guardians", "Radiant Buffed Monk Builds Corrupted Invader", 213),
			new ("Sun Staff", "Weapons > Streamer", "Fire Cooked Obelisk Builds Chaotic Necromancer", 400),
			new ("Sword of Valor (Blue)", "Weapons > Squire", "Wild Beloved Obelisk Yeets Shattered Marauder", 46),
			new ("Sword of Valor (Green)", "Weapons > Squire", "Fragile Luminous Banner Repairs Cooked Pack", 46),
			new ("Sword of Valor (Red)", "Weapons > Squire", "Shattered Enchanted Spike Pops Fragile Goblin", 46),
			new ("Tabula Rasa", "Accessories > Exclusive Armor Pieces", "Enchanted Fragile Trap Farms Goated Dragon", 300),
			new ("Talay's Doom", "Weapons > Squire", "Mythic Ancient Tower Clutches Goated Berserker", 64),
			new ("Terra's Magicite Brooch", "Accessories > Hats", "Tactical Mythic Champion Repels Heroic Invader", 40),
			new ("Tess", "Pets > Exclusives", "Heroic Fragile Squire Wipes Buffed Demon", 463),
			new ("The Cavalry", "Pets > DPS", "Fire Fragile Fireball Builds Fortified Pack", 63),
			new ("The Devil's Poolskimmer", "Weapons > Monk", "Ancient Cooked Tower Locks Sweaty Assassin", 52),
			new ("The Downpour", "Weapons > Apprentice", "Fragile Luminous Trap Burns Hardened Raider", 261),
			new ("The Goblinator", "Pets > Exclusives", "Heroic Locked Defender Boosts Hardened Horde", 393),
			new ("The Prince's Glove", "Weapons > Squire", "Locked Endless Aura Spams Radiant Wretch", 79),
			new ("The Queen of Fire", "Pets > Exclusives", "Cracked Radiant Barricade Builds Mid Fiend", 75),
			new ("The Rainmaker", "Weapons > Apprentice", "Mythic Mythic Tower Fortifies Shattered Assassin", 270),
			new ("Thermopylae's Wrath", "Weapons > Exclusive", "Grim Enchanted Lightning Yeets Fire Dragon", 80),
			new ("Thorn of Nature", "Weapons > Monk", "Tilted Corrupted Lightning Deletes Heroic Pack", 69),
			new ("Thread of Destiny", "Accessories > Bracers", "Mythic Nerfed Warden Deletes Sweaty Fiend", 80),
			new ("Thread of Life", "Accessories > Exclusives", "Wild Ancient Sigil Throws Tilted Raider", 95),
			new ("Tinkerer's Demise", "Weapons > Squire", "Grim Cooked Forge Snowballs Radiant Ravager", 148),
			new ("To Froya", "Weapons > Huntress", "Mythic Corrupted Barricade Camps Drippy Pillager", 125),
			new ("Toy Sword", "Weapons > Squire", "Tactical Fire Huntress Repairs Endless Goblin", 53),
			new ("Trick or Treater", "Pets > Collectibles", "Tilted Mythic Crystal Fortifies Beloved Horde", 100),
			new ("Ultimate Crystalline Defender", "Accessories > Shields", "Ancient Brutal Trap Burns Mid Invader", 93),
			new ("Ultimate Dungeon Defender", "Accessories > Shields", "Ancient Brutal Trap Burns Mid Invader", 560),
			new ("Umbriel", "Pets > Builder", "Tilted Enchanted Vanguard Farms Wild Abomination", 90),
			new ("Unstoppable Jewel Mask", "Accessories > Mid End Masks", "Buffed Fortified Lightning Summons Wild Marauder", 65),
			new ("Valentine's Patch Celebration", "Accessories > High End Hats", "Ancient Locked Apprentice Pops Cooked Fiend", 528),
			new ("Valentine's Patch Celebration", "Accessories > High End Hats", "Drippy Fortified Aura Fortifies Enchanted Spider", 528), // 2023
			new ("Vamp's Delight", "Weapons > Monk", "Shiny Fire Defender Boosts Grim Warlock", 50),
			new ("Vanadis", "Weapons > Exclusive", "Juicy Enchanted Beacon Camps Locked Kobold", 129),
			new ("Victoria", "Pets > Exclusives", "Shiny Mythic Fireball Burns Ancient Brood", 908),
			new ("Vile Lord's Clutch", "Accessories > Bracers", "Hardened Hardened Builder Shocks Drippy Goblin", 47),
			new ("Vortex Hammer", "Weapons > Squire", "Buffed Tilted Sentinel Repairs Luminous Assassin", 54),
			new ("Vortex Shield", "Accessories > Shields", "Hardened Chaotic Warden Summons Buffed Dragon", 98),
			new ("War Bonnet", "Accessories > Mid End Hats", "Tactical Fire Sentinel Farms Fortified Minion", 71),
			new ("Waterfall", "Weapons > Apprentice", "Hardened Shattered Armory Explodes Fragile Wyvern", 75),
			new ("Web of Love", "Weapons > Huntress", "Brutal Hardened Huntress Pops Goated Destroyer", 49),
			new ("White Mage", "Pets > DPS", "Beloved Juicy Protector Builds Ancient Swarm", 243),
			new ("Woodland Prison", "Weapons > Squire", "Hardened Mid Sigil Fortifies Drippy Beast", 119),
			new ("Xenon's Shell Pole", "Weapons > Monk", "Fortified Fire Core Shocks Cooked Kobold", 45),
			new ("Yeti", "Pets > DPS", "Buffed Radiant Beacon Deletes Cooked Invader", 250),
			new ("Yggdrashield", "Accessories > Exclusives", "Swift Hardened Tower Wins Mid Marauder", 307),
			new ("YGK's Extended Meat Carver", "Weapons > Squire", "Fire Tactical Barricade Yeets Drippy Spider", 41),
			new ("Zappy Rainbows", "Weapons > Exclusive", "Heroic Ancient Core Shocks Enchanted Goblin", 319),
			new ("Zygomatic Sword", "Weapons > Exclusive", "Fire Buffed Trap Shocks Wild Berserker", 254)
		};
	}
}
